server:
  port: 8000

spring:
  profiles:
    active: dev
---

spring:
  application:
    name: bulletin-board-back
  security:
    user:
      name: ${USER}
      password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: list
  cache:
    disabled: true
  model-and-view-allowed: true
jwt:
  issuer: ${JWT_ISSUER}
  access-key: ${JWT_ACCESS_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-key: ${JWT_REFRESH_KEY}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://${DB_HOST_FOR_DEV:localhost}:${DB_PORT_FOR_DEV:3307}/${DB_NAME_FOR_DEV:bulletin_board}
    username: ${DB_USERNAME_FOR_DEV}
    password: ${DB_PASSWORD_FOR_DEV}

cors:
  allowed-origins: ${CORS_ALLOWED_DOMAIN_FOR_DEV}
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

cors:
  allowed-origins: ${CORS_ALLOWED_DOMAIN}