server:
  port: 8000
spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: bulletin-board-back
  security:
    user:
      name: ${USER}
      password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bulletin_board
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: list
  cache:
    disabled: true
  model-and-view-allowed: true
jwt:
  issuer: ${JWT_ISSUER}
  access-key: ${JWT_ACCESS_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-key: ${JWT_REFRESH_KEY}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}